spring.application.name=imagejobs
spring.datasource.url=jdbc:postgresql://localhost:5432/imagejobs
spring.datasource.username=imagejobs
spring.datasource.password=imagejobs
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true